// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "farrel",
    "email": "farrel@mail.com",
    "password": "farrel123456",
    "confPassword": "farrel123456",
    "role": "admin",
}